/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;
import java.sql.*;
import java.sql.Connection;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author musta
 */
public class KayıtOlForm extends javax.swing.JFrame {

    /**
     * Creates new form KayıtOlForm
     */
    public KayıtOlForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAdSoyad = new javax.swing.JTextField();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        btnKayıtOl = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("KAYIT OLMA PANELİ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 40, 360, 43);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 690, 110);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Tel No.:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 340, 80, 40);

        txtNumara.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtNumara);
        txtNumara.setBounds(210, 340, 170, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Ad ve Soyad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 140, 140, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Kullanıcı Adı:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 140, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Şifre:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 240, 60, 40);

        txtAdSoyad.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtAdSoyad);
        txtAdSoyad.setBounds(210, 140, 170, 40);

        txtKullaniciAdi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtKullaniciAdi);
        txtKullaniciAdi.setBounds(210, 190, 170, 40);

        txtSifre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtSifre);
        txtSifre.setBounds(210, 240, 170, 40);

        btnKayıtOl.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnKayıtOl.setText("KAYIT OL");
        btnKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayıtOlActionPerformed(evt);
            }
        });
        getContentPane().add(btnKayıtOl);
        btnKayıtOl.setBounds(210, 390, 290, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("E-Mail:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 290, 80, 40);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(210, 290, 170, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayıtOlActionPerformed
        
        String adsoyad= txtAdSoyad.getText();
        String kullaniciadi = txtKullaniciAdi.getText();
        String sifre =txtSifre.getText();
        String email = txtEmail.getText();
        String numara = txtNumara.getText();
        
        
        try{
            
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/dbJava_Proje","postgres","1234");
            String sql ="insert into login (adsoyad,kullaniciadi,sifre,email,numara) values('"+adsoyad+"','"+kullaniciadi+"','"+sifre+"','"+email+"','"+numara+"')";
            Statement st = con.createStatement();
            int x = st.executeUpdate(sql);
            if (x == 0) {
                        JOptionPane.showMessageDialog(null, "kayıt Yoktur");
                    } else {
                        JOptionPane.showMessageDialog(null, "Kayıt Oluşturuldu.");
                        LoginForm fr = new LoginForm();
            fr.show();
            this.hide();
            con.close();
            }
       
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnKayıtOlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayıtOlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayıtOlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayıtOlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayıtOlForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayıtOlForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKayıtOl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdSoyad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JTextField txtNumara;
    private javax.swing.JTextField txtSifre;
    // End of variables declaration//GEN-END:variables
}
