/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author musta
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm1
     
     */
    public LoginForm()   {
        initComponents();
        
        
             
       
         
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JPasswordField();
        btnKayıtOl = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(718, 540));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(718, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(718, 540));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("GİRİŞ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 280, 210, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Şifre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 240, 76, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Kullanıcı Adı:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 200, 150, 30);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jCheckBox1.setText("Şifreyi Göster");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(340, 250, 91, 19);

        txtKullaniciAdi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtKullaniciAdi.setToolTipText("");
        txtKullaniciAdi.setName("txtKullaniciAdi"); // NOI18N
        txtKullaniciAdi.setPreferredSize(new java.awt.Dimension(70, 70));
        txtKullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKullaniciAdiActionPerformed(evt);
            }
        });
        jPanel1.add(txtKullaniciAdi);
        txtKullaniciAdi.setBounds(220, 200, 110, 30);

        txtSifre.setMinimumSize(new java.awt.Dimension(70, 70));
        jPanel1.add(txtSifre);
        txtSifre.setBounds(220, 240, 110, 30);

        btnKayıtOl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKayıtOl.setText("KAYIT OL");
        btnKayıtOl.setBorderPainted(false);
        btnKayıtOl.setContentAreaFilled(false);
        btnKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayıtOlActionPerformed(evt);
            }
        });
        jPanel1.add(btnKayıtOl);
        btnKayıtOl.setBounds(310, 320, 120, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 2, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("M&M STÜDYO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 40, 420, 48);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(500, 150, 64, 86);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(580, 20, 90, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 20, 90, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 680, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
          try{
             
             Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/dbJava_Proje","postgres","1234");
             String kullaniciadi= txtKullaniciAdi.getText();
             String sifre = txtSifre.getText();
             
             Statement st = con.createStatement();
             
             
             String sql ="select * from login where kullaniciadi='" +kullaniciadi+"' and sifre='"+ sifre+"'";
             
             ResultSet rs = st.executeQuery(sql);
             
             if(rs.next()){
                 
                 String GönderilenVeri=txtKullaniciAdi.getText();
                 new AnaForm(GönderilenVeri).setVisible(true);
                 
                 this.hide();
                 
             }
             else{
                 JOptionPane.showMessageDialog(this,"Kullanıcı Adı veya Şifre Yanlış");
                 txtKullaniciAdi.setText("");
                 txtSifre.setText("");
                 
             }
             con.close();
                     
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
        
        

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            txtSifre.setEchoChar((char)0);
            
        }
        else{
            txtSifre.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayıtOlActionPerformed
        KayıtOlForm fr = new KayıtOlForm();
        fr.show();
        this.hide();
    }//GEN-LAST:event_btnKayıtOlActionPerformed

    private void txtKullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKullaniciAdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKayıtOl;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
