/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author musta
 */
public class OkculukAnaForm extends javax.swing.JFrame {

    /**
     * Creates new form AnaForm
     */
    public OkculukAnaForm() {
        initComponents();
           }
    public OkculukAnaForm(String GelenV){
        initComponents();
         JOptionPane.showMessageDialog(null, "Hedeflere Tıklayarak Attığınız Okların Yerini Görebilrisniz.");
        lblOkAtan.setText(GelenV + " Ok Atıyor." );
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblOkAtan = new javax.swing.JLabel();
        btnHedefUc = new javax.swing.JButton();
        btnHedefBir = new javax.swing.JButton();
        btnHedefIki = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblPuanToplam = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        jButton38 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(750, 550));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("OKÇULUK OYUNU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 740, 80);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/hedef1.png"))); // NOI18N
        jPanel6.add(jLabel7);
        jLabel7.setBounds(220, 140, 100, 100);

        lblOkAtan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOkAtan.setText("-");
        jPanel6.add(lblOkAtan);
        lblOkAtan.setBounds(10, 10, 230, 30);

        btnHedefUc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/hedef1.png"))); // NOI18N
        btnHedefUc.setPreferredSize(new java.awt.Dimension(100, 100));
        btnHedefUc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHedefUcActionPerformed(evt);
            }
        });
        jPanel6.add(btnHedefUc);
        btnHedefUc.setBounds(40, 260, 100, 100);

        btnHedefBir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/hedef1.png"))); // NOI18N
        btnHedefBir.setPreferredSize(new java.awt.Dimension(100, 100));
        btnHedefBir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHedefBirActionPerformed(evt);
            }
        });
        jPanel6.add(btnHedefBir);
        btnHedefBir.setBounds(40, 40, 100, 100);

        btnHedefIki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/hedef1.png"))); // NOI18N
        btnHedefIki.setPreferredSize(new java.awt.Dimension(100, 100));
        btnHedefIki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHedefIkiActionPerformed(evt);
            }
        });
        jPanel6.add(btnHedefIki);
        btnHedefIki.setBounds(40, 150, 100, 100);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(60, 90, 180, 380);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("OK AT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 420, 150, 50);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(null);

        lblPuanToplam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPuanToplam.setText("0");
        jPanel4.add(lblPuanToplam);
        lblPuanToplam.setBounds(100, 340, 30, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("2.");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 70, 20, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("3.");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 100, 20, 17);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("TOPLAM:");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(10, 340, 80, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("SKOR TABLOSU:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(6, 6, 130, 17);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("1.");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 40, 20, 17);

        lblA1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblA1.setText("0");
        jPanel4.add(lblA1);
        lblA1.setBounds(40, 40, 20, 17);

        lblA2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblA2.setText("0");
        jPanel4.add(lblA2);
        lblA2.setBounds(70, 40, 20, 17);

        lblA3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblA3.setText("0");
        jPanel4.add(lblA3);
        lblA3.setBounds(100, 40, 20, 17);

        lblB1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblB1.setText("0");
        jPanel4.add(lblB1);
        lblB1.setBounds(40, 70, 20, 17);

        lblB2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblB2.setText("0");
        jPanel4.add(lblB2);
        lblB2.setBounds(70, 70, 20, 17);

        lblB3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblB3.setText("0");
        jPanel4.add(lblB3);
        lblB3.setBounds(100, 70, 20, 17);

        lblC1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblC1.setText("0");
        jPanel4.add(lblC1);
        lblC1.setBounds(40, 100, 20, 17);

        lblC3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblC3.setText("0");
        jPanel4.add(lblC3);
        lblC3.setBounds(100, 100, 20, 17);

        lblC2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblC2.setText("0");
        jPanel4.add(lblC2);
        lblC2.setBounds(70, 100, 20, 17);

        jButton38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton38.setText("BİTİR");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton38);
        jButton38.setBounds(150, 320, 110, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(420, 100, 260, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int count=0, toplam=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(count==0){
          int a = (5+(int)(Math.random()*5));
          int b = (5+(int)(Math.random()*5));
          int c = (5+(int)(Math.random()*5));
        lblA1.setText(String.valueOf(a));
        lblA2.setText(String.valueOf(b));
        lblA3.setText(String.valueOf(c));
        count++;
        toplam += (a+b+c);
        }else if(count==1){
            int a = (5+(int)(Math.random()*5));
          int b = (5+(int)(Math.random()*5));
          int c = (5+(int)(Math.random()*5));
        lblB1.setText(String.valueOf(a));
        lblB2.setText(String.valueOf(b));
        lblB3.setText(String.valueOf(c));
        count ++;
        toplam += (a+b+c);
        
       }else if(count==2){
           int a = (5+(int)(Math.random()*5));
          int b = (5+(int)(Math.random()*5));
          int c = (5+(int)(Math.random()*5));
        lblC1.setText(String.valueOf(a));
        lblC2.setText(String.valueOf(b));
        lblC3.setText(String.valueOf(c));
        count ++;
        toplam += (a+b+c);
        lblPuanToplam.setText(String.valueOf(toplam));
        }
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHedefBirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHedefBirActionPerformed
        String GönderilenVeri=lblA1.getText();
        String GönderilenVeri2 =lblA2.getText();
        String GönderilenVeri3 = lblA3.getText();
        new HedefForm1(GönderilenVeri,GönderilenVeri2,GönderilenVeri3).setVisible(true);
    }//GEN-LAST:event_btnHedefBirActionPerformed

    private void btnHedefIkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHedefIkiActionPerformed
       String GönderilenVeri=lblB1.getText();
        String GönderilenVeri2 =lblB2.getText();
        String GönderilenVeri3 = lblB3.getText();
        new HedefForm2(GönderilenVeri,GönderilenVeri2,GönderilenVeri3).setVisible(true);
    }//GEN-LAST:event_btnHedefIkiActionPerformed

    private void btnHedefUcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHedefUcActionPerformed
        String GönderilenVeri=lblC1.getText();
        String GönderilenVeri2 =lblC2.getText();
        String GönderilenVeri3 = lblC3.getText();
        new HedefForm3(GönderilenVeri,GönderilenVeri2,GönderilenVeri3).setVisible(true);
    }//GEN-LAST:event_btnHedefUcActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        AnaForm fr = new AnaForm();
        fr.show();
        this.hide();
    }//GEN-LAST:event_jButton38ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OkculukAnaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHedefBir;
    private javax.swing.JButton btnHedefIki;
    private javax.swing.JButton btnHedefUc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblOkAtan;
    private javax.swing.JLabel lblPuanToplam;
    // End of variables declaration//GEN-END:variables
}
