/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author demirel.muhammed
 */
public class ruletmasasi extends javax.swing.JFrame {

    String A[][][]= {{{" "," "},{"0","0"},{" "," "}},{{"siyah","1"},{"kırmızı","2"},{"siyah","3"}},
        {{"kırmızı","4"},{"siyah","5"},{"kırmızı","6"}}, {{"siyah","7"},{"kırmızı","8"},{"siyah","9"}},
        {{"kırmızı","10"},{"siyah","11"}, {"kırmızı","12"}},{{"siyah","13"},{"kırmızı","14"},{"siyah","15"}},
        {{"kırmızı","16"}, {"siyah","17"},{"kırmızı","18"}},{{"siyah","19"},{"kırmızı","20"},{"siyah","21"}},
        {{"kırmızı","22"}, {"siyah","23"},{"kırmızı","24"}},{{"siyah","25"},{"kırmızı","26"},{"siyah","27"}},
        {{"kırmızı","28"}, {"siyah","29"},{"kırmızı","30"}},{{"siyah","31"},{"kırmızı","32"},{"siyah","33"}},
        {{"kırmızı","34"}, {"siyah","35"},{"kırmızı","36"}}};
    String b,c="a",d="a";//b bizim bastığımız değer, c dizideki siyah ve kırmızı renklerini d ise sayıları tutyor
    int sayi1=0,sayi2=0;
    int tek =0;
    int secilensayi=0;
    int bakiye = 1000;//bunu genel skordan çekersek mükemmel olur
    int bahis = 300;
    public ruletmasasi() {
        initComponents();
        txtyazi.setVisible(false);
        pnlsonuc.setVisible(false);
        lblsonucyazisi.setVisible(false);
        lblsonuc.setVisible(false);
        btncevir.setVisible(false);
        btnyeniden.setVisible(false);
        lblkazanc.setVisible(false);
        txtyazi.setVisible(true);
        lblbakiye2.setText(""+bakiye);
        lblbakiye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsonuc = new javax.swing.JPanel();
        lblsonuc = new javax.swing.JLabel();
        lblsonucyazisi = new javax.swing.JLabel();
        btnyeniden = new javax.swing.JButton();
        btncevir = new javax.swing.JButton();
        lblsecim = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblkazanc = new javax.swing.JLabel();
        lblbakiye = new javax.swing.JLabel();
        txtyazi = new javax.swing.JTextField();
        btnred = new javax.swing.JButton();
        btnblack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        lblbakiye2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnodd = new javax.swing.JButton();
        btneven = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(null);

        pnlsonuc.setBackground(new java.awt.Color(0, 153, 51));
        pnlsonuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlsonucMouseClicked(evt);
            }
        });
        pnlsonuc.setLayout(null);

        lblsonuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblsonuc.setText("0");
        pnlsonuc.add(lblsonuc);
        lblsonuc.setBounds(420, 210, 180, 20);

        lblsonucyazisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblsonucyazisi.setText("GELEN SONUÇ :");
        pnlsonuc.add(lblsonucyazisi);
        lblsonucyazisi.setBounds(270, 210, 140, 20);

        btnyeniden.setText("YENİDEN OYNA");
        btnyeniden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenidenActionPerformed(evt);
            }
        });
        pnlsonuc.add(btnyeniden);
        btnyeniden.setBounds(210, 250, 120, 40);

        btncevir.setText("ÇARKI ÇEVİR");
        btncevir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncevirActionPerformed(evt);
            }
        });
        pnlsonuc.add(btncevir);
        btncevir.setBounds(210, 250, 110, 40);

        lblsecim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsecim.setText("0");
        pnlsonuc.add(lblsecim);
        lblsecim.setBounds(150, 200, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("SEÇİMİNİZ:");
        pnlsonuc.add(jLabel4);
        jLabel4.setBounds(40, 200, 110, 30);

        lblkazanc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblkazanc.setText("0");
        pnlsonuc.add(lblkazanc);
        lblkazanc.setBounds(270, 80, 110, 30);

        lblbakiye.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblbakiye.setText("0");
        pnlsonuc.add(lblbakiye);
        lblbakiye.setBounds(200, 80, 90, 30);

        getContentPane().add(pnlsonuc);
        pnlsonuc.setBounds(40, 50, 600, 390);

        txtyazi.setEditable(false);
        txtyazi.setBackground(new java.awt.Color(0, 0, 0));
        txtyazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtyazi.setForeground(new java.awt.Color(255, 255, 255));
        txtyazi.setText("oynamak istediğiniz oyun türünü seçin...");
        txtyazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyaziActionPerformed(evt);
            }
        });
        getContentPane().add(txtyazi);
        txtyazi.setBounds(0, 440, 700, 50);

        btnred.setBorderPainted(false);
        btnred.setContentAreaFilled(false);
        btnred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnredActionPerformed(evt);
            }
        });
        getContentPane().add(btnred);
        btnred.setBounds(280, 380, 80, 60);

        btnblack.setBorderPainted(false);
        btnblack.setContentAreaFilled(false);
        btnblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblackActionPerformed(evt);
            }
        });
        getContentPane().add(btnblack);
        btnblack.setBounds(370, 380, 80, 60);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 240, 40, 80);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 160, 40, 70);

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 70, 40, 80);

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(140, 240, 40, 80);

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 160, 40, 70);

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(140, 70, 40, 80);

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(190, 240, 40, 80);

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(190, 160, 40, 70);

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(190, 70, 40, 80);

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(230, 240, 40, 80);

        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(230, 160, 40, 70);

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(230, 70, 40, 80);

        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(280, 243, 40, 70);

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(280, 163, 40, 70);

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(280, 73, 40, 70);

        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(330, 240, 30, 70);

        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(330, 163, 30, 70);

        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(330, 83, 30, 60);

        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(370, 240, 40, 70);

        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(370, 163, 30, 70);

        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(380, 80, 30, 70);

        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(420, 83, 30, 60);

        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(420, 243, 30, 70);

        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(420, 163, 30, 60);

        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(460, 243, 40, 70);

        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(460, 163, 40, 70);

        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(470, 80, 30, 60);

        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(510, 243, 30, 70);

        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(510, 163, 30, 70);

        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(510, 83, 30, 60);

        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(550, 243, 40, 80);

        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(550, 160, 40, 70);

        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(560, 80, 30, 60);

        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(600, 243, 30, 70);

        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(600, 163, 30, 70);

        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(600, 83, 30, 60);

        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(40, 160, 50, 70);

        lblbakiye2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblbakiye2.setText("0");
        getContentPane().add(lblbakiye2);
        lblbakiye2.setBounds(120, 10, 100, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("BAKİYE: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(27, 10, 100, 22);

        btnodd.setBorderPainted(false);
        btnodd.setContentAreaFilled(false);
        btnodd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoddActionPerformed(evt);
            }
        });
        getContentPane().add(btnodd);
        btnodd.setBounds(460, 380, 90, 60);

        btneven.setBorderPainted(false);
        btneven.setContentAreaFilled(false);
        btneven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevenActionPerformed(evt);
            }
        });
        getContentPane().add(btneven);
        btneven.setBounds(190, 380, 72, 50);

        jButton38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton38.setText("BİTİR");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(580, 10, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/rulet2.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtyaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyaziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyaziActionPerformed

    private void btnblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblackActionPerformed
       b="siyah";
       bahis=100;
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       c=A[sayi1][sayi2][0];
        lblsonuc.setText(c);
        
    }//GEN-LAST:event_btnblackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
b="2";
        pnlsonuc.setVisible(true); 
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        b="5";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        b="3";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        b="8";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       b="9";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        b="11";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        b="1";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       b="7";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        b="20";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       b="4";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        b="6";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      b="10";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     b="12";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       b="13";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        b="14";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        b="15";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       b="16";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        b="17";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       b="18";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        b="19";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        b="21";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        b="22";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        b="23";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        b="24";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        b="25";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        b="26";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        b="27";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        b="28";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
       b="29";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
       b="30";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        b="31";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        b="32";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        b="33";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        b="34";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
       b="35";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
       b="36";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void btnredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnredActionPerformed
        b="kırmızı";
        bahis=100;
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       c=A[sayi1][sayi2][0];
        lblsonuc.setText(c);
    }//GEN-LAST:event_btnredActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        b="0";
        pnlsonuc.setVisible(true);
        lblsecim.setText(b);
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*12));
        sayi2 = (0+(int)(Math.random()*3));
        if((sayi1==0)&&(sayi2==0))
            { sayi1 = (int)(Math.random()*12);
                sayi2 = (int)(Math.random()*3); } 
        else if((sayi1==0)&&(sayi2==2)) 
                { sayi1 = (int)(Math.random()*12); 
                sayi2 = (int)(Math.random()*3); 
                    }
       d=A[sayi1][sayi2][1];
        lblsonuc.setText(d);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void btncevirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncevirActionPerformed
         lblsonucyazisi.setVisible(true);
            
       lblsonuc.setVisible(true);
       btncevir.setVisible(false);
       btnyeniden.setVisible(true);
        if(tek==0){
        if(bakiye>300)
        {
     
       if(lblsecim.equals('0'))
       {
           lblkazanc.setText("Kazandın ");
           bakiye+=(bahis*4);
           lblbakiye.setText(""+(bahis*4));
           lblbakiye2.setText(""+bakiye);
           
       }
       else if(b.equals(c))
               {
                    lblkazanc.setText("Kazandın ");
           bakiye+=bahis;
           lblbakiye.setText(""+bahis);
           lblbakiye2.setText(""+bakiye);
               }
       else if(b.equals(d))
               {
                    lblkazanc.setText("Kazandın ");
           bakiye+=(bahis*4);
           lblbakiye.setText(""+(bahis*4));
           lblbakiye2.setText(""+bakiye);
               }
       else
       {
            lblkazanc.setText("Kaybettin ");
            bakiye-=bahis;
            lblbakiye.setText(""+bahis);
            lblbakiye2.setText(""+bakiye);
       }
       
       
        }
        else if(bakiye<300)
        {
            JOptionPane.showMessageDialog(null, "Bakiye yetersiz");
            
        }
        }
        else if(tek==1)
        {
            if(secilensayi==1)
            {
                 if(sayi1%2==0)
        {
            lblkazanc.setText("kaybettin");
            bakiye-=bahis;
            lblbakiye.setText(""+bahis);
            lblbakiye2.setText(""+bakiye);
        }
        else if(sayi1%2!=0)
        {
            lblkazanc.setText("kazandın");
            bakiye+=bahis;
           lblbakiye.setText(""+bahis);
           lblbakiye2.setText(""+bakiye);
        }
                
            }
            else if(secilensayi==2){
                 if(sayi1%2==0)
        {
            lblkazanc.setText("kazandın");
            bakiye+=bahis;
           lblbakiye.setText(""+bahis);
           lblbakiye2.setText(""+bakiye);
        }
        else if(sayi1%2!=0)
        {
            lblkazanc.setText("kaybettin");
            bakiye-=bahis;
            lblbakiye.setText(""+bahis);
            lblbakiye2.setText(""+bakiye);
        }
            }
             secilensayi=0;   
            tek=0;
        }
        lblkazanc.setVisible(true);
       lblbakiye.setVisible(true);
                      lblsonucyazisi.setVisible(true);

      
       
        
    }//GEN-LAST:event_btncevirActionPerformed

    private void btnyenidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenidenActionPerformed
        pnlsonuc.setVisible(false);
        btnyeniden.setVisible(false);
        lblsonuc.setVisible(false);
        lblkazanc.setVisible(false);
        lblkazanc.setVisible(false);
               lblbakiye.setVisible(false);
               lblsonucyazisi.setVisible(false);
               if(bakiye<300)
               {
                   JOptionPane.showMessageDialog(null, "Bakiye yetersiz");
            AnaForm fr = new AnaForm();
            fr.show();
             this.hide();
               }  

        
    }//GEN-LAST:event_btnyenidenActionPerformed

    private void pnlsonucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsonucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlsonucMouseClicked

    private void btnoddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoddActionPerformed
       tek=1;
       secilensayi=1;
        pnlsonuc.setVisible(true);
        lblsecim.setText("Tek sayi");
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*36));
        lblsonuc.setText(""+sayi1);
       
    }//GEN-LAST:event_btnoddActionPerformed

    private void btnevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevenActionPerformed
 tek=1;
 secilensayi=2;
        pnlsonuc.setVisible(true);
        lblsecim.setText("çift sayi");
        btncevir.setVisible(true);
        sayi1 = (0+(int)(Math.random()*36));
        lblsonuc.setText(""+sayi1);
       
        
    }//GEN-LAST:event_btnevenActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
       AnaForm fr = new AnaForm();
        fr.show();
        this.hide();
    }//GEN-LAST:event_jButton38ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ruletmasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ruletmasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ruletmasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ruletmasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruletmasasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnblack;
    private javax.swing.JButton btncevir;
    private javax.swing.JButton btneven;
    private javax.swing.JButton btnodd;
    private javax.swing.JButton btnred;
    private javax.swing.JButton btnyeniden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblbakiye;
    private javax.swing.JLabel lblbakiye2;
    private javax.swing.JLabel lblkazanc;
    private javax.swing.JLabel lblsecim;
    private javax.swing.JLabel lblsonuc;
    private javax.swing.JLabel lblsonucyazisi;
    private javax.swing.JPanel pnlsonuc;
    private javax.swing.JTextField txtyazi;
    // End of variables declaration//GEN-END:variables
}
