/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;

/**
 *
 * @author demirel.muhammed
 */
public class Ruletform extends javax.swing.JFrame {

    /**
     * Creates new form Ruletform
     */
    int count =0;
    public Ruletform() {
        initComponents();
        
    }
   
    public Ruletform(String GelenV){
        
        initComponents();
        lbloyuncu.setText(GelenV);
        lbloyuncu.setVisible(false);
       btnbasla.setVisible(true);
        btnileri.setVisible(false);
        jButton1.setVisible(false);
         jButton2.setVisible(false);
          jButton3.setVisible(false);
          jScrollPane1.setVisible(false);
          jScrollPane2.setVisible(false);
          jScrollPane3.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbasla = new javax.swing.JButton();
        btnileri = new javax.swing.JButton();
        lbloyuncu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        btnbasla.setText("BAŞLA");
        btnbasla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaslaActionPerformed(evt);
            }
        });
        getContentPane().add(btnbasla);
        btnbasla.setBounds(310, 400, 90, 30);

        btnileri.setBackground(new java.awt.Color(0, 0, 0));
        btnileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnileri.setForeground(new java.awt.Color(255, 255, 255));
        btnileri.setText("ileri...");
        btnileri.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnileri.setBorderPainted(false);
        btnileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnileriActionPerformed(evt);
            }
        });
        getContentPane().add(btnileri);
        btnileri.setBounds(620, 360, 80, 80);

        lbloyuncu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbloyuncu.setForeground(new java.awt.Color(255, 255, 255));
        lbloyuncu.setText("jLabel2");
        getContentPane().add(lbloyuncu);
        lbloyuncu.setBounds(230, 360, 120, 15);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("M&M Kum**hanesine hoşgeldin                         . Ben bu kumarhanenin\n ortaklarınden Melik Demirel.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 360, 660, 91);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Büyük emekler verip kurduğumuz bu güzel mekanımızda ne oynamak istersin ?");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 360, 650, 91);

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea3.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Aaaa malesef yeni açıldığımız için sadece rulet masalarımız var sana bol şanslar diliyorum");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 360, 650, 91);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/ben1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 190, 120, 250);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/ben2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 190, 120, 250);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/ben3.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 190, 120, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/m&m cazino.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnileriActionPerformed
  count++;
  if(count == 1)
  {
      lbloyuncu.setVisible(false);
      jButton1.setVisible(false);
        jScrollPane1.setVisible(false);
        jButton2.setVisible(true);
        jScrollPane2.setVisible(true);
  }
  else if(count == 2)
  {
      jButton1.setVisible(false);
        jScrollPane1.setVisible(false);
        jButton2.setVisible(false);
        jScrollPane2.setVisible(false);
        jButton3.setVisible(true);
        jScrollPane3.setVisible(true);
      
  }
  else if(count ==3)
  {
      ruletmasasi fr = new ruletmasasi();
      fr.show();
      this.hide();
  }
  
    }//GEN-LAST:event_btnileriActionPerformed

    private void btnbaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaslaActionPerformed
        btnbasla.setVisible(false);
        jButton1.setVisible(true);
        jScrollPane1.setVisible(true);
        lbloyuncu.setVisible(true);
        btnileri.setVisible(true);

    }//GEN-LAST:event_btnbaslaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruletform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruletform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruletform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruletform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruletform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbasla;
    private javax.swing.JButton btnileri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lbloyuncu;
    // End of variables declaration//GEN-END:variables
}
