/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_proje;

import javax.swing.JOptionPane;

/**
 *
 * @author musta
 */
public class XOXForm extends javax.swing.JFrame {
String [] hucre = new String[9];
String [] skor = new String[10];
 

 
    public XOXForm() {
         initComponents();
        
    }
    public XOXForm(String GelenV){
        initComponents();
        lblOyuncu.setText(GelenV + " oynuyor");
         lblBiz.setVisible(true);
         btn1.setEnabled(false);
         btn2.setEnabled(false);
         btn3.setEnabled(false);
         btn4.setEnabled(false);
         btn5.setEnabled(false);
         btn6.setEnabled(false);
         btn7.setEnabled(false);
         btn8.setEnabled(false);
         btn9.setEnabled(false);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblBiz = new javax.swing.JLabel();
        btn9 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPcSkor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblOyuncu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblOyuncuSkor = new javax.swing.JLabel();
        btnBitir = new javax.swing.JButton();
        btnBasla1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setPreferredSize(null);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(null);

        lblBiz.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 48)); // NOI18N
        lblBiz.setText("M&M OYUN");
        jPanel3.add(lblBiz);
        lblBiz.setBounds(200, 10, 310, 110);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 0, 690, 130);

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(270, 370, 100, 100);

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(50, 150, 100, 100);

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(160, 150, 100, 100);

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(270, 150, 100, 100);

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(270, 260, 100, 100);

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(160, 260, 100, 100);

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(50, 260, 100, 100);

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(50, 370, 100, 100);

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(160, 370, 100, 100);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lblPcSkor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPcSkor.setText("0");
        jPanel1.add(lblPcSkor);
        lblPcSkor.setBounds(190, 100, 20, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("SKOR:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 10, 60, 40);

        lblOyuncu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblOyuncu.setText("OYUNCU:");
        jPanel1.add(lblOyuncu);
        lblOyuncu.setBounds(10, 60, 190, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("BİLGİSAYAR:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 100, 120, 40);

        lblOyuncuSkor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblOyuncuSkor.setText("0");
        jPanel1.add(lblOyuncuSkor);
        lblOyuncuSkor.setBounds(190, 60, 20, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 200, 220, 220);

        btnBitir.setText("Bitir");
        btnBitir.setPreferredSize(new java.awt.Dimension(104, 23));
        btnBitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitirActionPerformed(evt);
            }
        });
        getContentPane().add(btnBitir);
        btnBitir.setBounds(460, 420, 220, 30);

        btnBasla1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBasla1.setText("BAŞLA");
        btnBasla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasla1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBasla1);
        btnBasla1.setBounds(460, 160, 220, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int oyuncuskor = 0, bilgisayarskor=0 ,say=0 ,i=0;
   String ad ="";
    private void btnBasla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasla1ActionPerformed
         btn1.setEnabled(true);
         btn2.setEnabled(true);
         btn3.setEnabled(true);
         btn4.setEnabled(true);
         btn5.setEnabled(true);
         btn6.setEnabled(true);
         btn7.setEnabled(true);
         btn8.setEnabled(true);
         btn9.setEnabled(true);
        btnBasla1.setVisible(false);
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        oyun_durum=true;
        butonsifirla();
        degersifirla();
        

    }//GEN-LAST:event_btnBasla1ActionPerformed

    private void btnBitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitirActionPerformed
        AnaForm fr = new AnaForm();
        fr.show();
        this.hide();
    }//GEN-LAST:event_btnBitirActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
    btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn1.setEnabled(false);  
     hucre[0]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
          btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn2.setEnabled(false);  
     hucre[1]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
          btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn3.setEnabled(false);  
     hucre[2]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
         btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn4.setEnabled(false);  
     hucre[3]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
          btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn5.setEnabled(false);  
     hucre[4]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
          btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn6.setEnabled(false);  
     hucre[5]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
          btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn7.setEnabled(false);  
     hucre[6]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
         btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn8.setEnabled(false);  
     hucre[7]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
          btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/X.png")));
    btn9.setEnabled(false);  
     hucre[8]="x";
     say++;
     kontrol();
     bilgisayar_oyna();
    }//GEN-LAST:event_btn9ActionPerformed

    boolean oyun_durum = false;
    
    public void kontrol(){
        XOXForm f = new XOXForm();
        if(say<9){
            if("x".equals(hucre[0]) & "x".equals(hucre[4]) & "x".equals(hucre[8]) || "x".equals(hucre[2]) & "x".equals(hucre[4]) & "x".equals(hucre[6]) ||"x".equals(hucre[0]) & "x".equals(hucre[3]) & "x".equals(hucre[6]) ||"x".equals(hucre[1]) & "x".equals(hucre[4]) & "x".equals(hucre[7])||"x".equals(hucre[2]) & "x".equals(hucre[5]) & "x".equals(hucre[8])|| "x".equals(hucre[0]) & "x".equals(hucre[1]) & "x".equals(hucre[2])|| "x".equals(hucre[3]) & "x".equals(hucre[4]) & "x".equals(hucre[5])||"x".equals(hucre[6]) & "x".equals(hucre[7]) & "x".equals(hucre[8]) ){
                JOptionPane.showMessageDialog(f, "Oyuncu Kazandı");
                butonsifirla();
                degersifirla();
                oyuncuskor++;
                oyun_durum=true;
                lblOyuncuSkor.setText(String.valueOf(oyuncuskor));
            }
            else if( "o".equals(hucre[0]) & "o".equals(hucre[4]) & "o".equals(hucre[8]) || "o".equals(hucre[2]) & "o".equals(hucre[4]) & "o".equals(hucre[6]) ||"o".equals(hucre[0]) & "o".equals(hucre[3]) & "o".equals(hucre[6]) ||"o".equals(hucre[1]) & "o".equals(hucre[4]) & "o".equals(hucre[7])||"o".equals(hucre[2]) & "o".equals(hucre[5]) & "o".equals(hucre[8])|| "o".equals(hucre[0]) & "o".equals(hucre[1]) & "o".equals(hucre[2])|| "o".equals(hucre[3]) & "o".equals(hucre[4]) & "o".equals(hucre[5])||"o".equals(hucre[6]) & "o".equals(hucre[7]) & "o".equals(hucre[8]) ){
                JOptionPane.showMessageDialog(f, "Bilgisayar Kazandı");
               butonsifirla();
               degersifirla();
                bilgisayarskor++;
                oyun_durum=true;
                lblPcSkor.setText(String.valueOf(bilgisayarskor));
            }}   
            else if(say==9){
                
                JOptionPane.showMessageDialog(f, "Kazanan Yok");
                butonsifirla();
               degersifirla();
                 oyun_durum=true;
                
            }
            if(oyun_durum==false){
                btnBasla1.setVisible(true);
                
            }
            
            
        
    }
    
    public void butonsifirla(){
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/bos.png")));
        btn1.setEnabled(true);
         btn2.setEnabled(true);
         btn3.setEnabled(true);
         btn4.setEnabled(true);
         btn5.setEnabled(true);
         btn6.setEnabled(true);
         btn7.setEnabled(true);
         btn8.setEnabled(true);
         btn9.setEnabled(true);
    }
    public void degersifirla(){
    for(int j=0; j<9; j++){
        hucre[j]="";
        say=0;
    }
    oyun_durum=true;
}
    
    
    public void bilgisayar_oyna(){
        if(oyun_durum == true){
            int h=-1;
            boolean durum = false;
            do{
                h= (int)(Math.random()*9);
                if("x".equals(hucre[h])){
                    durum=false;
                }
                else if("o".equals(hucre[h])){
                     durum=false;
                }
                else {
                    durum= true;
                } 
            }
            while(durum==false);
            
            hucre[h]="o";
            say++;
            if(h==0) {  btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
            btn1.setEnabled(false);   }
else if(h==1)
{ btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
  btn2.setEnabled(false);     }    
else if(h==2) 
{  btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
                btn3.setEnabled(false);     }
else if(h==3){  btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
         btn4.setEnabled(false);     }
else if(h==4)      {      btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
         btn5.setEnabled(false);      }
else if(h==5)      {      btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
         btn6.setEnabled(false);      }
else if(h==6)      {      btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
         btn7.setEnabled(false);      }
else if(h==7)      {      btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
         btn8.setEnabled(false);      }
else if(h==8)      {      btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resmiler/O.png")));
              btn9.setEnabled(false);
}
            kontrol();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XOXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XOXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XOXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XOXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XOXForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBasla1;
    private javax.swing.JButton btnBitir;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBiz;
    private javax.swing.JLabel lblOyuncu;
    private javax.swing.JLabel lblOyuncuSkor;
    private javax.swing.JLabel lblPcSkor;
    // End of variables declaration//GEN-END:variables
}
